### ISSUE TITLE
Feedback: Postmortem i1

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/iFarra#10]
Pessoal, nós monitores estamos realizando um rodízio para deixar a avaliação de vocês mais justa. Sobre o postmortem de vocês a única coisa que eu senti falta foi da atribuição das atividades. É importante deixar claro quem foi que participou de cada uma das atividades que vocês listaram lá. Segue o modelo adaptado do postmortem que vocês podem usar: https://github.com/IF977/monitoria-if977-SI/blob/master/Postmortem.md

Vlw!

**Comment by ccsguedes** [comment]
Bom dia, Jorge.

Todas as atividades estão atribuídas a um ou mais membros da equipe.
(Tanto as dessa iteração quanto as ações que ainda serão executadas). Segue
print comprovando.


Em 26 de mai de 2017 9:25 AM, "Jorge Linhares" <notifications@github.com>
escreveu:

**Comment by jorgehclinhares** [comment]
Não recebi o print

**Comment by ccsguedes** [comment]
Vê se foi agora.

Em 26 de mai de 2017 9:58 AM, "Jorge Linhares" <notifications@github.com>
escreveu:

**Comment by jorgehclinhares** [comment]
Não, acho que você tem que enviar pelo github mesmo

**Comment by ccsguedes** [comment]
Esse print é do que está no github. É a iteração 2 que enviamos na quarta.

Em 26 de mai de 2017 10:03 AM, "Jorge Linhares" <notifications@github.com>
escreveu:

**Comment by ccsguedes** [comment]
Jorge, eu confundi os postmortems. Pensei que era a correção do 2.
Desculpe.

Em 26 de mai de 2017 10:09 AM, "Caio Cesar Silva Guedes" <ccsg@cin.ufpe.br>
escreveu:
