### ISSUE TITLE
Feedback: Uso das Labels

### ISSUE THREAD

**Issue by jorgehclinhares** [IF977/iFarra#11]
Acredito que foi passado na monitoria de github mas só reforçando o cadastramento e uso das Labels, em caso de dúvidas é só falar. Lembrando que a nomenclatura e as suas respectivas cores devem ser respeitadas (como mostrado na image).

![6cf291b6-24dc-11e7-9cb2-a325c1979945](https://cloud.githubusercontent.com/assets/11631238/26494938/ac6a8a96-41f7-11e7-9d58-3384a2c0a65d.png)

https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by jorgehclinhares** [comment]
Não entendi, vocês aplicaram o que eu falei?

**Comment by mateusc42** [comment]
Sim, Jorge. Estamos utilizando as Labels e utilizamos nas iterações anteriores mas não sabíamos que era para deixas as issues como 'Open'.

**Comment by jorgehclinhares** [comment]
Não é para deixar open. O que eu estou querendo dizer é que vocês precisam editar as labels que tem aqui no github para as labels que vocês podem ver na imagem que eu anexei ai em cima. Respeitando nomenclatura/cor. Vocês devem ir em: https://github.com/IF977/iFarra/labels e editar.

**Comment by mateusc42** [comment]
Perdão, Jorge. Atualizamos os nomes com suas respectivas cores. Obrigado.

**Comment by jorgehclinhares** [comment]
Sem bronca :D
