### ISSUE TITLE
Correção postmortem iteração 2

### ISSUE THREAD

**Issue by rafjordao** [IF977/iFarra#26]
## - **Postmortem iteração 2**

- ### _Atraso na entrega do postmortem_ -> não (nota base 10.0)

- ### _O que estava planejado_ -> faltou indicar responsáveis por cada objetivo planejado -> -0.5
     como deveria estar?

| Atividade | Atribuição |
| --- | --- |
| Mussum Ipsum, cacilds vidis litro abertis. Si num tem leite então bota uma pinga aí cumpadi! | `@pessoa1`, `@pessoa2`, `@pessoa3` |
| Mussum Ipsum, cacilds vidis litro abertis. Si num tem leite então bota uma pinga aí cumpadi! | `@todos` |
- ### _O que foi feito_ -> ok

- ### _O que não foi feito_ -> ok

- ### _Planejado para próxima iteração_ -> ok

- ### _Lições aprendidas_ -> ok

## Nota final: 9.5
          10.0 - 0.5 = 9.5

**Comment by ps1312** [comment]
Obrigado, Rafael!
